### ISSUE TITLE
Run terminates with error while on conda

### ISSUE THREAD

**Issue by Anto007** [BigDataBiology/macrel#17]
I get this error during the middle of running macrel on conda:

Traceback (most recent call last):
  File "/user/conda_macrel_env/bin/macrel", line 11, in <module>
    sys.exit(main())
  File "/user/conda_macrel_env/lib/python3.7/site-packages/macrel/main.py", line 282, in main
    do_predict(args, tdir)
  File "/user/conda_macrel_env/lib/python3.7/site-packages/macrel/main.py", line 241, in do_predict
    fs)
  File "/user/conda_macrel_env/lib/python3.7/site-packages/macrel/AMP_predict.py", line 7, in predict
    model1 = pickle.load(gzip.open(model1, 'rb'))
ModuleNotFoundError: No module named 'sklearn'

The commandline that I used after activating the conda macrel environment is this:
macrel contigs --fasta test_bacterium_genome.fasta --output test_contigs

I would appreciate your feedback here.

**Comment by celiosantosjr** [comment]
Hi Anto007,

Could you clarify some details? Is your installation from source or directly from conda container?

Best,
Celio

**Comment by luispedro** [comment]
We will fix the underlying issue (that the conda package does not declare `scikit-learn` as a dependency), but, in the meanwhile, please try running `conda install scikit-learn`

**Comment by luispedro** [comment]
Closing here now that the new conda version is available

@Anto007 thank you for the report, it was helpful. Please report any further issues

**Comment by Anto007** [comment]
Thank you very much! It works fine now. I would like to make a few suggestions (if I may):

1) Can you mention in the README and manual what are the expected output files and a brief description of what kind of information they contain? This will be helpful for new users. Also, some elaboration on the type of infomration being represented in the macrel.out.prediction output file will be welcome. For example, from your experience, AMP_probability or Hemolytic_probability scores above what value should be taken with more confidence by the users?

2) Perhaps it can be considered a bit odd that the 'macrel.out.prediction' output file is gzipped? Have you ever ended with really bulky 'macrel.out.prediction' files? It's even more odd when considering the fact that the more bulkier *.faa files in the output directory are not gzipped?

3) Can you make a clear mention of the availability of test datasets in your README & Manual and how the outputs from this test data will look like or exactly where to find these example test results? I did find test datasets and their outputs at macrel/tests/ but it could be more convenient for new users if you make a direct mention of it.

Thanks again for your prompt support!

**Comment by Anto007** [comment]
One more thing: '--outtag' in the manual should be replaced with '--tag'

**Comment by luispedro** [comment]
Thanks, these are all good suggestions.

**Comment by luispedro** [comment]
The gzipping of some files and not others is a bit of laziness on our part: because `pandas` (the library we use) does implicit gzip when you save the TSV file, we did it, but for the fasta files, it would have been an extra step.
