### ISSUE TITLE
Bioconda release for Mac OS

### ISSUE THREAD

**Issue by somakchowdhury** [BigDataBiology/macrel#19]
Hi,

Any chance that you are considering MACREL release for macOS? 

Thanks

Somak

**Comment by luispedro** [comment]
We are a bit dependent on https://github.com/ngless-toolkit/ngless/issues/125 for a full release, but 95% of the functionality should work from a `pip` install using Python (I know this is not fully satisfactory, so I'm leaving it open here, but it's a workaround)

**Comment by martinklapper** [comment]
would it be possible to put the application and its dependencies in a docker image that one could download?

**Comment by luispedro** [comment]
We've finally resolved this issue and macrel is available for osx on bioconda!
