### ISSUE TITLE
Contigs mode is not returning AMPs

### ISSUE THREAD

**Issue by celiosantosjr** [BigDataBiology/macrel#20]
It seems that the methionine excision, when N-terminal is not working when macrel is called by this module. This can be affecting the prediction. Also, the option --keep-negatives seems to be default when calling this mode.

**Comment by luispedro** [comment]
Is there an example that can be posted publicly?

The test at `https://github.com/BigDataBiology/macrel/tree/master/tests/contigs` should test for these behaviours
