### ISSUE TITLE
macrel peptides - version problems

### ISSUE THREAD

**Issue by GaioTransposon** [BigDataBiology/macrel#25]
Hi Luis, 

I am having a problem with running macrel peptides. 
macrel contigs it's running fine, but I am guessing it's because it didn't get to the peptide part yet. 

Steps I ran: 
```
conda create -n macrel_env
conda activate macrel_env
conda install -c bioconda macrel
macrel get-examples
macrel peptides \
    --fasta example_seqs/expep.faa.gz \
    --output out_peptides \
    -t 4
```

error message of the last command being:
```
rpy2.rinterface_lib.embedded.RRuntimeError: Error: package or namespace load failed for ‘Peptides’:
 package ‘Peptides’ was installed before R 4.0.0: please re-install it
```

I tried a few re-install attampts, none of which worked. Hope you can suggest a solution. 

Thank you,
Dany

**Comment by luispedro** [comment]
Thanks for the report. @celiosantosjr @psj1997 : can you have a look at what's going on here?

**Comment by celiosantosjr** [comment]
Hi Gaio, 

Could you send me the following complementary info in order to me understand the environment?

- Which is your conda version?
- Which is the R version in your conda arc and also in your installed environment?

Thank you in advance.

**Comment by luispedro** [comment]
The same commands above worked for me on Linux (and AWS machine).

Could you (@GaioTransposon) be using Mac?

**Comment by GaioTransposon** [comment]
using Linux...

**Comment by luispedro** [comment]
Great that this was solved for you.

I am still going to leave the issue open until we figure out how to make it work for everyone without extra dancing
