### ISSUE TITLE
clustering macrel's output

### ISSUE THREAD

**Issue by GaioTransposon** [BigDataBiology/macrel#31]
Hi Luis, 

I am using cd-hit to cluster Macrel's output. Do you have better ideas? 
Out of 70k predicted AMPs, only about half of them get clustered. Can you advice on tools to use to cluster Macrel's output? 

This is my current use of cd-hit on Macrel's output: 
```
cd-hit -i macrel.out.prediction.all.fasta -o /.../.../cd_hit_onMacrel98 -c 0.98 -n 5 -d 0 -M 30000 -T 10
```
Thank you
Dany

**Comment by luispedro** [comment]
Just a note that for more open ended Qs rather than issues, you can use the mailing list https://groups.google.com/g/ampsphere-users

CD-HIT has worked well for us (somewhat surprisingly, as it was not designed for short peptides), but I note that you are using a very strict cutoff (`-c 0.98`).

**Comment by luispedro** [comment]
I'm going to close as an issue, but feel free to follow up on the mailing list...
