### ISSUE TITLE
Retrain Macrel model?

### ISSUE THREAD

**Issue by cmerenstein** [BigDataBiology/macrel#36]
Is it possible to retrain the model used in Macrel with new training data?

I'm trying to optimize specifically for shorter peptides (< 50 aa), but the training data used in the Macrel paper (downloaded from the original Bhadra 2018 paper) has a lot of much longer peptides. I found that retraining the model in amPEPpy with only shorter peptides improved accuracy on my data specifically, I was hoping to try the same with Macrel.

Thanks,
Carter

**Comment by celiosantosjr** [comment]
Definitely, you can use the scripts available in the ```train/``` folder for retraining the models with other fasta files. We implemented the model you asked for as the option ```-model 'l50'```. It was made with peptides of 50 res. or less filtered from the initial datasets. Detailed information about the statistics of the new models is available in the log of the merged branch.

Briefly, the l50 option for AMPs prediction maintains accuracy of 92.1% and an MCC of 0.74. The accuracy and MCC for the prediction of hemolytic peptides were 94.5% and 0.889, respectively. In both cases, the precision was still high (99.5% for AMPs and 94.5% for hemolytic peptides).

If you have suggestions of alternative approaches or datasets to be used in current models, we invite you to message us also via [discussion group](mailto:ampsphere-users@googlegroups.com).

Best,
Celio

**Comment by luispedro** [comment]
We played around with this idea, but empirically it did not seem to improve the results, so we decided to not include it in a release.

We would still be interested in exploring alternative classification approaches.
