### ISSUE TITLE
Consider using `pyrodigal` for small ORFs detection

### ISSUE THREAD

**Issue by althonos** [BigDataBiology/macrel#53]
Hi! 

I normally don't like making this kind of advertisement out of the blue, but this could be of interest to you: in the last two years I developed Python bindings for Prodigal in a package named [`pyrodigal`](https://github.com/althonos/pyrodigal), and I just released a new version that supports setting a custom minimum gene length. Maybe this could save you the trouble of having to compile and maintain a customized Prodigal fork just for this feature. 

Cheers!

**Comment by celiosantosjr** [comment]
Hi Martin,

Thank you for your suggestion. This is actually very relevant for the tool.
We might switch to pyrodigal in the next big updates of Macrel, but for
now, the current approach still seems functional.

Best regards,
Celio
