### ISSUE TITLE
The prediction input file problem

### ISSUE THREAD

**Issue by aslangabriel99** [BigDataBiology/macrel#61]
Hi, I have tested the gut 16s amplicon of  a lot of host such as duck, blacksoldierfly,silkworm, housefly, et .al and some enviromental metageomes sequnced on illumina by paire ends. Unfortunately there is no result in prediction gz files. I also tested with the example data. The result is normal. I don't know what's the problem

**Comment by celiosantosjr** [comment]
Dear aslangabriel99,

I am sorry to hear that. However, 16S amplicon is not an appropriate input
for Macrel. It uses metagenomic datasets, therefore, it is expected 16S
data do not return any result.
For the metagenomes sequenced from environmental sources, one possible
option is trying to use the flag '--keep-negatives' to verify if any
peptide was spotted. The input influences
heavily the results in this case, and as Macrel is a high precision method,
its recall is not as extensive as in other lower precision methods. If you
are willing to try, please let me know
what the results were. Besides, for questions and other discussions like
this one, you can always go to our discussion
***@***.***> forum.

Best,
Celio
